# Generated by Django 4.2.7 on 2023-11-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
                ('stuff', models.TextField()),
                ('emojis', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard')], default='', max_length=10)),
                ('tags', models.TextField(blank=True, null=True)),
                ('methods', models.TextField(blank=True, null=True)),
                ('tools', models.TextField()),
            ],
        ),
    ]
