# Generated by Django 4.2.7 on 2023-11-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_stuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='type',
            field=models.CharField(blank=True, choices=[('meat', 'meat'), ('vegi', 'vegetable'), ('staple', 'staple'), ('tools', 'tools')], default='', max_length=10),
        ),
    ]
