# Generated by Django 4.2.7 on 2023-11-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_stuff_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='emojis',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='methods',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='stuff',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tools',
        ),
        migrations.AddField(
            model_name='recipe',
            name='stuff',
            field=models.ManyToManyField(limit_choices_to={'type__in': ['meat', 'vegi', 'staple']}, related_name='related_recipes', to='recipes.stuff'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tools',
            field=models.ManyToManyField(limit_choices_to={'type': 'tools'}, related_name='tool_recipes', to='recipes.stuff'),
        ),
    ]
